# Generated by Django 5.1.2 on 2024-12-19 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63, verbose_name='タイトル')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='終了時刻')),
                ('location', models.CharField(blank=True, max_length=63, verbose_name='場所')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='提出締切')),
                ('ann_status', models.CharField(choices=[('public', '公開'), ('limited', '限定公開'), ('private', '非公開')], default='public', max_length=7, verbose_name='告知公開設定')),
                ('rec_status', models.CharField(choices=[('public', '公開'), ('limited', '限定公開'), ('private', '非公開')], default='private', max_length=7, verbose_name='記録公開設定')),
                ('ann_desc', models.TextField(blank=True, max_length=511, null=True, verbose_name='告知説明')),
                ('ended', models.BooleanField(default=False, verbose_name='終了済み')),
                ('rec_desc', models.TextField(blank=True, max_length=511, null=True, verbose_name='記録説明')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='司会者')),
            ],
        ),
        migrations.CreateModel(
            name='Tanka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='詠草')),
                ('guest_author', models.CharField(default='', max_length=63, verbose_name='ゲスト筆名')),
                ('status', models.CharField(choices=[('public', '公開'), ('limited', '限定公開'), ('private', '非公開')], default='private', max_length=7, verbose_name='公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='筆名')),
            ],
        ),
        migrations.CreateModel(
            name='TankaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='タイトル')),
                ('description', models.TextField(max_length=127, verbose_name='説明')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='TankaListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('tanka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utakais.tanka')),
                ('tanka_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utakais.tankalist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tankalist',
            name='tankas',
            field=models.ManyToManyField(through='utakais.TankaListItem', to='utakais.tanka', verbose_name='短歌リスト'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user', models.CharField(default='', max_length=63, verbose_name='ゲスト参加者')),
                ('is_observer', models.BooleanField(default=False, verbose_name='見学者フラグ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utakais.event', verbose_name='参加イベント')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
                ('tanka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utakais.tanka', verbose_name='詠草')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='tankalistitem',
            constraint=models.UniqueConstraint(fields=('tanka_list', 'tanka'), name='unique_tanka_in_list'),
        ),
    ]
