# Generated by Django 5.1.2 on 2024-12-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='guest_contact',
            field=models.EmailField(default='empty@example.com', max_length=254, verbose_name='ゲスト参加者のメールアドレス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanka',
            name='guest_author',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='ゲスト筆名'),
        ),
    ]
