# Generated by Django 5.1.2 on 2025-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0002_participant_guest_contact_alter_tanka_guest_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eisou_doc',
            field=models.FileField(null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='eisou_pdf',
            field=models.FileField(null=True, upload_to='events/'),
        ),
    ]
