# Generated by Django 5.1.2 on 2024-12-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0002_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ann_is_public',
            field=models.BooleanField(default='False', verbose_name='告知公開設定'),
        ),
        migrations.AddField(
            model_name='event',
            name='rec_is_public',
            field=models.BooleanField(default='False', verbose_name='記録公開設定'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ann_desc',
            field=models.TextField(blank=True, max_length=511, null=True, verbose_name='告知説明'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rec_desc',
            field=models.TextField(blank=True, max_length=511, null=True, verbose_name='記録説明'),
        ),
    ]
