# Generated by Django 5.1.2 on 2024-12-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0003_event_ann_is_public_event_rec_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ann_is_public',
            field=models.BooleanField(default=True, verbose_name='告知公開設定'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(blank=True, verbose_name='提出締切'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=63, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rec_is_public',
            field=models.BooleanField(default=False, verbose_name='記録公開設定'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=63, verbose_name='タイトル'),
        ),
    ]
