# Generated by Django 5.1.2 on 2025-01-08 02:43

import utakais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0004_alter_tanka_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eisou_number',
            field=models.PositiveIntegerField(default=0, verbose_name='詠草一覧版数'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eisou_doc',
            field=models.FileField(null=True, upload_to=utakais.models.Event.file_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='eisou_pdf',
            field=models.FileField(null=True, upload_to=utakais.models.Event.file_path),
        ),
    ]
