# Generated by Django 5.1.2 on 2024-12-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0004_alter_event_ann_is_public_alter_event_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ann_is_public',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rec_is_public',
        ),
        migrations.AddField(
            model_name='event',
            name='ann_status',
            field=models.CharField(choices=[('public', '公開'), ('limited', '限定公開'), ('private', '非公開')], default='public', max_length=7, verbose_name='告知公開設定'),
        ),
        migrations.AddField(
            model_name='event',
            name='rec_status',
            field=models.CharField(choices=[('public', '公開'), ('limited', '限定公開'), ('private', '非公開')], default='private', max_length=7, verbose_name='記録公開設定'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提出締切'),
        ),
    ]
