# Generated by Django 5.1.2 on 2024-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0005_remove_event_ann_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
    ]
