# Generated by Django 5.1.2 on 2025-02-14 17:03

import django.core.validators
import django.db.models.deletion
import utakais.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0005_event_eisou_number_alter_event_eisou_doc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eisou_doc',
            field=models.FileField(null=True, upload_to=utakais.models.Event.file_path, validators=[django.core.validators.FileExtensionValidator(['docx'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='eisou_pdf',
            field=models.FileField(null=True, upload_to=utakais.models.Event.file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='guest_contact',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='guest_user',
            field=models.CharField(default='', max_length=63, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前'),
        ),
    ]
