# Generated by Django 5.1.2 on 2025-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utakais', '0007_participant_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanka',
            name='guest_author',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='筆名'),
        ),
    ]
